export const JAWI_TOPICS = [
    {
        id: 1,
        title: "Kata Kerja & Perbuatan",
        titleEng: "Verbs & Actions",
        words: [
            { rumi: "Baca", jawi: "باچا", emoji: "📖", eng: "Read" },
            { rumi: "Tulis", jawi: "توليس", emoji: "✍️", eng: "Write" },
            { rumi: "Lari", jawi: "لاري", emoji: "🏃", eng: "Run" },
            { rumi: "Lompat", jawi: "لومڤت", emoji: "🤸", eng: "Jump" },
            { rumi: "Makan", jawi: "ماكن", emoji: "🍽️", eng: "Eat" },
            { rumi: "Minum", jawi: "مينوم", emoji: "🥤", eng: "Drink" },
            { rumi: "Tidur", jawi: "تيدور", emoji: "😴", eng: "Sleep" },
            { rumi: "Jalan", jawi: "جالن", emoji: "🚶", eng: "Walk" },
            { rumi: "Duduk", jawi: "دودوق", emoji: "🪑", eng: "Sit" },
            { rumi: "Mandi", jawi: "مندي", emoji: "🚿", eng: "Bathe" },
            { rumi: "Masak", jawi: "ماسق", emoji: "🍳", eng: "Cook" },
            { rumi: "Basuh", jawi: "باسوه", emoji: "🧼", eng: "Wash" },
            { rumi: "Bawa", jawi: "باوا", emoji: "🎒", eng: "Carry" },
            { rumi: "Tolak", jawi: "تولق", emoji: "✋", eng: "Push" },
            { rumi: "Tarik", jawi: "تاريق", emoji: "🎣", eng: "Pull" },
            { rumi: "Gunting", jawi: "ݢونتيڠ", emoji: "✂️", eng: "Cut" },
            { rumi: "Lukis", jawi: "لوكيس", emoji: "🎨", eng: "Draw" },
            { rumi: "Nyanyi", jawi: "ڽاڽي", emoji: "🎤", eng: "Sing" },
            { rumi: "Tari", jawi: "تاري", emoji: "💃", eng: "Dance" },
            { rumi: "Jaga", jawi: "جاݢ", emoji: "👀", eng: "Watch" }
        ],
        color: "#4ECDC4" // Teal
    },
    {
        id: 2,
        title: "Anggota Badan & Manusia",
        titleEng: "Body Parts & People",
        words: [
            { rumi: "Mata", jawi: "مات", emoji: "👁️", eng: "Eye" },
            { rumi: "Kaki", jawi: "كاكي", emoji: "🦶", eng: "Foot" },
            { rumi: "Bahu", jawi: "باهو", emoji: "💪", eng: "Shoulder" },
            { rumi: "Jari", jawi: "جاري", emoji: "🖐️", eng: "Finger" },
            { rumi: "Muka", jawi: "موك", emoji: "🙂", eng: "Face" },
            { rumi: "Hati", jawi: "هاتي", emoji: "❤️", eng: "Heart" },
            { rumi: "Gigi", jawi: "ݢيݢي", emoji: "🦷", eng: "Tooth" },
            { rumi: "Gusi", jawi: "ݢوسي", emoji: "👄", eng: "Gums" },
            { rumi: "Kuku", jawi: "كوكو", emoji: "💅", eng: "Nail" },
            { rumi: "Dada", jawi: "دادا", emoji: "👕", eng: "Chest" },
            { rumi: "Lidah", jawi: "ليده", emoji: "👅", eng: "Tongue" },
            { rumi: "Perut", jawi: "ڤروت", emoji: "🤰", eng: "Stomach" },
            { rumi: "Ibu", jawi: "ايبو", emoji: "👩", eng: "Mother" },
            { rumi: "Ayah", jawi: "اية", emoji: "👨", eng: "Father" },
            { rumi: "Adik", jawi: "اديق", emoji: "👶", eng: "Sibling" },
            { rumi: "Abang", jawi: "ابڠ", emoji: "👦", eng: "Brother" },
            { rumi: "Guru", jawi: "ݢورو", emoji: "👩‍🏫", eng: "Teacher" },
            { rumi: "Murid", jawi: "موريد", emoji: "🎒", eng: "Student" },
            { rumi: "Kawan", jawi: "كاون", emoji: "🤝", eng: "Friend" },
            { rumi: "Orang", jawi: "اورڠ", emoji: "👥", eng: "Person" }
        ],
        color: "#FF6B6B" // Red
    },
    {
        id: 3,
        title: "Objek & Alatan",
        titleEng: "Objects & Tools",
        words: [
            { rumi: "Buku", jawi: "بوكو", emoji: "📕", eng: "Book" },
            { rumi: "Pensel", jawi: "ڤنسيل", emoji: "✏️", eng: "Pencil" },
            { rumi: "Meja", jawi: "ميجا", emoji: "🪑", eng: "Table" },
            { rumi: "Kerusi", jawi: "كروسي", emoji: "🪑", eng: "Chair" },
            { rumi: "Pintu", jawi: "ڤينتو", emoji: "🚪", eng: "Door" },
            { rumi: "Lampu", jawi: "لمڤو", emoji: "💡", eng: "Lamp" },
            { rumi: "Baju", jawi: "باجو", emoji: "👕", eng: "Shirt" },
            { rumi: "Kasut", jawi: "كاسوت", emoji: "👟", eng: "Shoes" },
            { rumi: "Beg", jawi: "بيݢ", emoji: "🎒", eng: "Bag" },
            { rumi: "Topi", jawi: "توڤي", emoji: "🧢", eng: "Hat" },
            { rumi: "Sudu", jawi: "سودو", emoji: "🥄", eng: "Spoon" },
            { rumi: "Gelas", jawi: "ݢلس", emoji: "🥃", eng: "Glass" },
            { rumi: "Bakul", jawi: "باقول", emoji: "🧺", eng: "Basket" },
            { rumi: "Kunci", jawi: "كونچي", emoji: "🔑", eng: "Key" },
            { rumi: "Kain", jawi: "كاين", emoji: "🧵", eng: "Cloth" },
            { rumi: "Jarum", jawi: "جاروم", emoji: "🪡", eng: "Needle" },
            { rumi: "Raga", jawi: "راݢ", emoji: "🧺", eng: "Wicker Basket" },
            { rumi: "Talam", jawi: "تالم", emoji: "🍽️", eng: "Tray" },
            { rumi: "Pena", jawi: "ڤينا", emoji: "🖊️", eng: "Pen" },
            { rumi: "Tali", jawi: "تالي", emoji: "🧶", eng: "Rope" }
        ],
        color: "#FFE66D" // Yellow
    },
    {
        id: 4,
        title: "Alam & Haiwan",
        titleEng: "Nature & Animals",
        words: [
            { rumi: "Bumi", jawi: "بومي", emoji: "🌍", eng: "Earth" },
            { rumi: "Bulan", jawi: "بولن", emoji: "🌙", eng: "Moon" },
            { rumi: "Awan", jawi: "اوان", emoji: "☁️", eng: "Cloud" },
            { rumi: "Hujan", jawi: "هوجن", emoji: "🌧️", eng: "Rain" },
            { rumi: "Laut", jawi: "لاوت", emoji: "🌊", eng: "Sea" },
            { rumi: "Bukit", jawi: "بوكيت", emoji: "⛰️", eng: "Hill" },
            { rumi: "Kayu", jawi: "كايو", emoji: "🪵", eng: "Wood" },
            { rumi: "Daun", jawi: "داون", emoji: "🍃", eng: "Leaf" },
            { rumi: "Akar", jawi: "اكر", emoji: "🪴", eng: "Root" },
            { rumi: "Bunga", jawi: "بوڠا", emoji: "🌺", eng: "Flower" },
            { rumi: "Kuda", jawi: "كودا", emoji: "🐎", eng: "Horse" },
            { rumi: "Rusa", jawi: "روسا", emoji: "🦌", eng: "Deer" },
            { rumi: "Ayam", jawi: "ايم", emoji: "🐔", eng: "Chicken" },
            { rumi: "Itik", jawi: "ايتيق", emoji: "🦆", eng: "Duck" },
            { rumi: "Ikan", jawi: "ايكن", emoji: "🐟", eng: "Fish" },
            { rumi: "Ular", jawi: "اولر", emoji: "🐍", eng: "Snake" },
            { rumi: "Katak", jawi: "كاتق", emoji: "🐸", eng: "Frog" },
            { rumi: "Burung", jawi: "بوروڠ", emoji: "🐦", eng: "Bird" },
            { rumi: "Singa", jawi: "سيڠا", emoji: "🦁", eng: "Lion" },
            { rumi: "Gajah", jawi: "ݢاجه", emoji: "🐘", eng: "Elephant" }
        ],
        color: "#8BC34A" // Green
    },
    {
        id: 5,
        title: "Sifat, Keadaan & Rasa",
        titleEng: "Qualities & Feelings",
        words: [
            { rumi: "Baik", jawi: "باءيق", emoji: "👍", eng: "Good" },
            { rumi: "Jahat", jawi: "جاهت", emoji: "😈", eng: "Evil" },
            { rumi: "Besar", jawi: "بسر", emoji: "🐘", eng: "Big" },
            { rumi: "Kecil", jawi: "كچيل", emoji: "🐜", eng: "Small" },
            { rumi: "Tinggi", jawi: "تيڠݢي", emoji: "🦒", eng: "Tall" },
            { rumi: "Rendah", jawi: "رنده", emoji: "🐁", eng: "Low" },
            { rumi: "Laju", jawi: "لاجو", emoji: "🚀", eng: "Fast" },
            { rumi: "Lambat", jawi: "لمبت", emoji: "🐢", eng: "Slow" },
            { rumi: "Panas", jawi: "ڤانس", emoji: "🔥", eng: "Hot" },
            { rumi: "Sejuk", jawi: "سجوق", emoji: "❄️", eng: "Cold" },
            { rumi: "Baru", jawi: "بارو", emoji: "✨", eng: "New" },
            { rumi: "Lama", jawi: "لاما", emoji: "🕰️", eng: "Old" },
            { rumi: "Kaya", jawi: "كاي", emoji: "💰", eng: "Rich" },
            { rumi: "Miskin", jawi: "ميسكين", emoji: "💸", eng: "Poor" },
            { rumi: "Suka", jawi: "سوك", emoji: "❤️", eng: "Like" },
            { rumi: "Duka", jawi: "دوك", emoji: "😢", eng: "Sad" },
            { rumi: "Nasi", jawi: "ناسي", emoji: "🍚", eng: "Rice" },
            { rumi: "Roti", jawi: "روتي", emoji: "🍞", eng: "Bread" },
            { rumi: "Gula", jawi: "ݢولا", emoji: "🍬", eng: "Sugar" },
            { rumi: "Susu", jawi: "سوسو", emoji: "🥛", eng: "Milk" }
        ],
        color: "#9D4EDD" // Purple
    }
];
