export const LOCALIZATION = {
    bm: {
        global: {
            home: 'Utama',
            back: 'Kembali',
            bmEng: 'Bahasa Malaysia / English'
        },
        home: {
            title: 'Iman Learning Hub',
            subtitle: 'Pilih subjek kegemaran anda! ✨',
            bmTitle: 'Bahasa Melayu',
            bmDesc: 'Belajar suku kata dan kosa kata!',
            mathTitle: 'Matematik',
            mathDesc: 'Adventure dengan nombor dan kira-kira!',
            jawiTitle: 'Jawi',
            jawiDesc: 'Mari mengenal huruf Jawi!',
            startButton: 'Mula Belajar!'
        },
        math: {
            hubTitle: 'Adventure Matematik',
            hubSubtitle: 'Pilih jenis permainan matematik anda! ✨',
            opsTitle: 'Operasi Matematik',
            opsDesc: 'Tambah, tolak, darab dan bahagi!',
            timeTitle: 'Tarikh / Masa',
            timeDesc: 'Belajar jam dan kalendar!',
            playNow: 'Main Sekarang!',
            comingSoon: 'Akan Datang'
        },
        jawi: {
            title: 'Pembelajaran Jawi',
            subtitle: 'Mari belajar mengenal Jawi bersama Iman! ✨',
            learnAlphabet: 'Mari Mengenali Huruf Jawi',
            learnSyllables: 'Permainan Suku Kata',
            learn100Words: '100 Perkataan Jawi',
            learnSpelling: 'Permainan Ejaan 100 Perkataan',
            testMatch: 'Permainan Padanan Jawi',
            comingSoon: 'Lebih banyak modul akan datang!',
            prev: 'Sebelum',
            next: 'Seterusnya',
            close: 'Tutup',
            alphabetTitle: 'Mengenal Huruf Jawi',
            noSyllableData: 'Tiada data suku kata untuk huruf ini.'
        },
        time: {
            title: 'Masa & Tarikh',
            monthLearning: 'Kenali Nama Bulan',
            monthLearningDesc: 'Belajar nama bulan dalam pelbagai bahasa!',
            timeAdventure: 'Pengembaraan Masa',
            timeAdventureDesc: 'Belajar membaca jam analog dan digital!',
            monthQuiz: 'Permainan Kuiz Bulan',
            monthQuizDesc: 'Belajar 12 bulan mengikut urutan!',
            selectGame: 'Pilih permainan anda! ✨'
        },
        monthsGame: {
            modeNumber: '🔢 No → Nama',
            modeName: '🗓️ Nama → Islam',
            modeIslamic: '☪️ Islam → Nama',
            quizABCD: 'ABCD',
            quizType: 'Taip',
            promptNumber: 'Apakah nama bulan ini?',
            promptName: 'Apakah bulan Islam bagi bulan ini?',
            promptIslamic: 'Apakah nama bulan ini?',
            refTitle: 'Nota Rujukan Bulan',
            refNo: 'No.',
            refNames: 'English/Malay',
            refIslamic: 'Islam',
            placeholder: 'Taip jawapan anda...',
            correctFeedback: 'Syabas! Jawapannya ialah',
            incorrectFeedback: 'Aduh! Jawapannya ialah',
            nextQuest: 'Soalan Seterusnya',
            correctInfoPrefix: 'Bulan',
            correctInfoSuffix: 'ialah'
        },
        monthLearningDetail: {
            title: 'Kenali Nama Bulan',
            subtitle: 'Klik pada bulan untuk melihat nama dalam pelbagai bahasa! ✨',
            monthPrefix: 'Bulan',
            labelEng: 'English',
            labelMalay: 'Malay',
            labelIslamic: 'Islamic',
            prev: 'Prev',
            next: 'Next',
            close: 'Tutup'
        },
        opsDetails: {
            title: 'Math Adventure dengan Iman',
            subtitle: 'Pilih cabaran anda!',
            diffLabel: 'Tahap Kesukaran',
            diffEasy: 'Senang',
            diffMedium: 'Sederhana',
            diffHard: 'Susah',
            quizLabel: 'Jenis Kuiz',
            quizMulti: '🔘 Pilihan Ganda',
            quizType: '⌨️ Taip Jawapan',
            practiceTitle: 'Latihan Sifir',
            practicePick: 'Pilih nombor untuk latihan:',
            clearAll: 'Kosongkan Semua',
            selectAll: 'Pilih Semua',
            startGame: 'Mula Permainan!',
            cancel: 'Batal',
            add: 'Tambah',
            sub: 'Tolak',
            mul: 'Darab',
            div: 'Bahagi',
            ran: 'Rawak'
        },
        quizArena: {
            loading: 'Memuatkan...',
            typePlaceholder: 'Taip jawapan anda...',
            correct: '✓ Betul!',
            incorrectLabel: 'Aduh! Jawapan betul ialah',
            nextQuestion: 'Soalan Seterusnya',
            streakInRow: 'berturut-turut!',
            streakMessages: [
                { min: 5, text: "Bagus!" },
                { min: 10, text: "Cemerlang!" },
                { min: 15, text: "Hebat!" },
                { min: 20, text: "Luar Biasa!" },
                { min: 25, text: "Menakjubkan!" },
                { min: 30, text: "BINTANG MUDA!" },
                { min: 35, text: "TIDAK TERKALAH!" },
                { min: 40, text: "GENIUS!" },
                { min: 45, text: "PAKAR MATEMATIK!" },
                { min: 50, text: "LEGENDA!" }
            ]
        },
        bmPage: {
            title: 'Bahasa Melayu',
            comingSoon: 'Akan datang tidak lama lagi! 🚀',
            desc: 'Kami sedang menyiapkan modul pembelajaran suku kata dan kosa kata yang menyeronokkan untuk anda.',
            backHome: 'Kembali ke Menu Utama'
        },
        clockGame: {
            loading: 'Memuatkan Jam...',
            modeAnalogDigital: '🕒 Analog → Digital',
            modeDigitalAnalog: '🔟 Digital → Analog',
            promptAnalog: 'Pukul berapakah ini?',
            promptDigital: 'Cari jam yang sepadan!',
            correctTimeLabel: 'Aduh! Waktu yang betul ialah',
            nextQuestion: 'Soalan Seterusnya',
            correct: 'Betul!'
        },
        jawiGames: {
            matchTitle: 'Permainan Padanan Jawi',
            syllablesTitle: 'Permainan Suku Kata Jawi',
            wordsTitle: '100 Perkataan Jawi',
            selectChar: 'Pilih sehingga 6 aksara untuk latihan padanan:',
            random6: 'Rawak 6',
            clearAll: 'Kosongkan Semua',
            selectAll: 'Pilih Semua',
            deselectAll: 'Nyahpilih Semua',
            startGame: 'Mula Permainan!',
            selectAtLeast2: 'Pilih sekurang-kurangnya 2',
            great: 'Hebat!',
            matchSummary: 'Anda memadankan {count} pasangan dalam {moves} langkah!',
            selection: 'Pilihan',
            restart: 'Mula Semula',
            playAgain: 'Main Lagi',
            matches: 'Padanan',
            moves: 'Langkah',
            chooseTopic: 'Pilih Topik',
            selectMode: 'Pilih Mod Permainan',
            typeRumi: 'Taip ejaan Rumi',
            whatSyllable: 'Apakah suku kata ini dalam Rumi?',
            correct: '✓ Betul!',
            incorrectLabel: 'Aduh! Jawapannya ialah',
            newGame: 'Permainan Baru',
            nextWord: 'Perkataan Seterusnya',
            nextQuestion: 'Soalan Seterusnya',
            gameOver: 'Permainan Tamat!',
            perfectScore: 'Skor Sempurna!',
            wellDone: 'Syabas!',
            totalScore: 'Jumlah Skor',
            randomMix: 'Campuran Rawak',
            selectAlphabets: 'Pilih Huruf',
            multiChoice: 'Pilihan Ganda',
            typeAnswer: 'Taip Jawapan',
            unlimited: 'Tanpa Had',
            loading: 'Memuatkan...',
            streakMessages: [
                { min: 5, text: "Teruskan!" },
                { min: 10, text: "Bagus!" },
                { min: 15, text: "Hebat!" },
                { min: 20, text: "Luar Biasa!" },
                { min: 25, text: "Menakjubkan!" },
                { min: 30, text: "BINTANG MUDA!" }
            ]
        }
    },
    eng: {
        global: {
            home: 'Home',
            back: 'Back',
            bmEng: 'English / Bahasa Malaysia'
        },
        home: {
            title: 'Iman Learning Hub',
            subtitle: 'Choose your favorite subject! ✨',
            bmTitle: 'Bahasa Melayu',
            bmDesc: 'Learn syllables and vocabulary!',
            mathTitle: 'Mathematics',
            mathDesc: 'Adventure with numbers and calculations!',
            jawiTitle: 'Jawi',
            jawiDesc: 'Let\'s learn Jawi characters!',
            startButton: 'Start Learning!'
        },
        math: {
            hubTitle: 'Mathematics Adventure',
            hubSubtitle: 'Choose your math game type! ✨',
            opsTitle: 'Math Operations',
            opsDesc: 'Addition, subtraction, multiplication and division!',
            timeTitle: 'Date / Time',
            timeDesc: 'Learn about clocks and calendars!',
            playNow: 'Play Now!',
            comingSoon: 'Coming Soon'
        },
        jawi: {
            title: 'Jawi Learning',
            subtitle: 'Let\'s learn Jawi with Iman! ✨',
            learnAlphabet: 'Learn Jawi Alphabet',
            learnSyllables: 'Alphabet Syllables Game',
            learn100Words: '100 Jawi Words',
            learnSpelling: '100 Words Spelling Game',
            testMatch: 'Jawi Match Game',
            comingSoon: 'More modules coming soon!',
            prev: 'Prev',
            next: 'Next',
            close: 'Close',
            alphabetTitle: 'Learn Jawi Alphabet',
            noSyllableData: 'No syllable data for this character.'
        },
        time: {
            title: 'Time & Date',
            monthLearning: 'Learn Month Names',
            monthLearningDesc: 'Learn month names in various languages!',
            timeAdventure: 'Time Adventure',
            timeAdventureDesc: 'Learn to read analog and digital clocks!',
            monthQuiz: 'Month Quiz Game',
            monthQuizDesc: 'Learn the 12 months in order!',
            selectGame: 'Select your game! ✨'
        },
        monthsGame: {
            modeNumber: '🔢 No → Name',
            modeName: '🗓️ Name → Islamic',
            modeIslamic: '☪️ Islamic → Name',
            quizABCD: 'ABCD',
            quizType: 'Type',
            promptNumber: 'What is this month?',
            promptName: 'What is the Islamic month?',
            promptIslamic: 'What is this month in English?',
            refTitle: 'Month Reference Note',
            refNo: 'No.',
            refNames: 'English/Malay',
            refIslamic: 'Islamic',
            placeholder: 'Type your answer...',
            correctFeedback: 'Great! The answer is',
            incorrectFeedback: 'Oops! The answer is',
            nextQuest: 'Next Question',
            correctInfoPrefix: 'Month',
            correctInfoSuffix: 'is'
        },
        monthLearningDetail: {
            title: 'Learning Month Names',
            subtitle: 'Click on a month to see its names in different languages! ✨',
            monthPrefix: 'Month',
            labelEng: 'English',
            labelMalay: 'Malay',
            labelIslamic: 'Islamic',
            prev: 'Prev',
            next: 'Next',
            close: 'Close'
        },
        opsDetails: {
            title: 'Math Adventure With Iman',
            subtitle: 'Select your challenge!',
            diffLabel: 'Difficulty',
            diffEasy: 'Easy',
            diffMedium: 'Medium',
            diffHard: 'Hard',
            quizLabel: 'Quiz Type',
            quizMulti: '🔘 Multiple Choice',
            quizType: '⌨️ Type Answer',
            practiceTitle: 'Practice Times Tables',
            practicePick: 'Select numbers to practice:',
            clearAll: 'Clear All',
            selectAll: 'Select All',
            startGame: 'Start Game!',
            cancel: 'Cancel',
            add: 'Addition',
            sub: 'Subtraction',
            mul: 'Multiplication',
            div: 'Division',
            ran: 'Random'
        },
        quizArena: {
            loading: 'Loading...',
            typePlaceholder: 'Type your answer...',
            correct: '✓ Correct!',
            incorrectLabel: 'Oops! The correct answer was',
            nextQuestion: 'Next Question',
            streakInRow: 'in a row!',
            streakMessages: [
                { min: 5, text: "You're Good!" },
                { min: 10, text: "Brilliant!" },
                { min: 15, text: "Awesome!" },
                { min: 20, text: "Fantastic!" },
                { min: 25, text: "Incredible!" },
                { min: 30, text: "SUPERSTAR!" },
                { min: 35, text: "UNSTOPPABLE!" },
                { min: 40, text: "GENIUS!" },
                { min: 45, text: "MATH WIZARD!" },
                { min: 50, text: "LEGENDARY!" }
            ]
        },
        bmPage: {
            title: 'Bahasa Melayu',
            comingSoon: 'Coming Soon! 🚀',
            desc: 'We are preparing fun modules for syllables and vocabulary for you.',
            backHome: 'Back to Home'
        },
        clockGame: {
            loading: 'Loading Clock...',
            modeAnalogDigital: '🕒 Analog → Digital',
            modeDigitalAnalog: '🔟 Digital → Analog',
            promptAnalog: 'What time is it?',
            promptDigital: 'Find the matching clock!',
            correctTimeLabel: 'Oops! The correct time was',
            nextQuestion: 'Next Question',
            correct: 'Correct!'
        },
        jawiGames: {
            matchTitle: 'Jawi Match Game',
            syllablesTitle: 'Jawi Syllables Game',
            wordsTitle: '100 Jawi Words',
            selectChar: 'Select up to 6 characters to practice matching:',
            random6: 'Random 6',
            clearAll: 'Clear All',
            selectAll: 'Select All',
            deselectAll: 'Deselect All',
            startGame: 'Start Game!',
            selectAtLeast2: 'Select at least 2',
            great: 'Great!',
            matchSummary: 'You matched {count} pairs in {moves} moves!',
            selection: 'Selection',
            restart: 'Restart',
            playAgain: 'Play Again',
            matches: 'Matches',
            moves: 'Moves',
            chooseTopic: 'Choose a Topic',
            selectMode: 'Select Game Mode',
            typeRumi: 'Type the Rumi spelling',
            whatSyllable: 'What is this syllable in Rumi?',
            correct: '✓ Correct!',
            incorrectLabel: 'Oops! The answer is',
            newGame: 'New Game',
            nextWord: 'Next Word',
            nextQuestion: 'Next Question',
            gameOver: 'Game Over!',
            perfectScore: 'Perfect Score!',
            wellDone: 'Well Done!',
            totalScore: 'Total Score',
            randomMix: 'Random Mix',
            selectAlphabets: 'Select Alphabets',
            multiChoice: 'Multiple Choice',
            typeAnswer: 'Type Answer',
            unlimited: 'Unlimited',
            loading: 'Loading...',
            streakMessages: [
                { min: 5, text: "Keep it up!" },
                { min: 10, text: "Great Job!" },
                { min: 15, text: "Awesome!" },
                { min: 20, text: "Fantastic!" },
                { min: 25, text: "Amazing!" },
                { min: 30, text: "SUPERSTAR!" }
            ]
        }
    }
};
